name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup_flutter:
    name: Set up Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        
      - name: Check current directory
        run: |
          echo "Current directory: $PWD"
          ls -la

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test test/band_members_section_test.dart --coverage

      - name: Convert coverage to CSV
        run: |
          DART_SDK="$RUNNER_TOOL_CACHE/flutter-sdk/bin/cache/dart-sdk"
          COVERAGE="$RUNNER_TOOL_CACHE/flutter-sdk/.pub-cache/bin/coverage"
          $DART_SDK/bin/dart $COVERAGE format_coverage --lcov --in=coverage/lcov.info --out=coverage/lcov.csv --packages=.packages --report-on=lib/

  convert_coverage:
    name: Convert coverage to HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install csv-html-table package
        run: npm install csv-html-table

      - name: Convert coverage to HTML
        run: npx csv-html-table coverage/lcov.csv -o coverage/lcov.html

  publish_artifact:
    name: Publish HTML artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Publish HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: Coverage report
          path: coverage/lcov.html
