name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test test/band_members_section_test.dart --coverage=coverage

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: coverage/lcov.info

      - name: Convert coverage to HTML
        run: |
          dart run coverage:format_coverage --lcov --in=coverage/lcov.info --out=coverage/lcov_report.info --packages=.packages --report-on=lib/
          dart run coverage:coverage_html --in=coverage/lcov_report.info --out=coverage/lcov-report

      - name: Publish HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: Coverage report
          path: coverage/lcov-report
