name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup_flutter:
    name: Set up Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        
      - name: Check current directory
        run: |
          echo "Current directory: $PWD"
          ls -la

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test test/band_members_section_test.dart --coverage

  publish_coverage:
    name: Publish coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Publish coverage
        uses: actions/upload-artifact@v2
        with:
          name: Coverage report
          path: coverage
